import { describe, expect, it } from "vitest";
import { buildReactionMapFromGraphIndex, toReactionMapWorkerInput, type ReactionMapExplicitInput } from "../src/index";

const feature = (reactionId: string, overrides: Partial<ReactionMapExplicitInput["reaction_features"][number]> = {}): ReactionMapExplicitInput["reaction_features"][number] => ({ reaction_entity_id: reactionId, document_id: "doc-1", reaction_signature: overrides.reaction_signature ?? "sig-a", participant_signature: overrides.participant_signature ?? "A=>B", fingerprint_status: overrides.fingerprint_status ?? "not_available", chemistry_feature_ref_ids: overrides.chemistry_feature_ref_ids ?? [], cluster_keys: overrides.cluster_keys ?? [{ basis: "reaction_signature", key: overrides.reaction_signature ?? "sig-a" }, { basis: "reaction_family", key: overrides.reaction_family ?? "oxidation" }, { basis: "procedure_signature", key: overrides.procedure_signature ?? "add>heat" }, { basis: "condition_signature", key: overrides.condition_signature ?? "solvent=MeOH" }], changed_variable_fields: [], controlled_variable_fields: [], condition_signature: overrides.condition_signature ?? "solvent=MeOH", procedure_signature: overrides.procedure_signature ?? "add>heat", reaction_family: overrides.reaction_family ?? "oxidation", route_id: overrides.route_id });

describe("reaction map builder", () => {
  it("creates deterministic cluster summaries by basis", () => { const layout = buildReactionMapFromGraphIndex({ reaction_features: [feature("rxn-2"), feature("rxn-1")] }); expect(layout.clusters.map((cluster) => cluster.basis)).toEqual(["reaction_signature", "procedure_signature", "condition_signature", "reaction_family"]); expect(layout.clusters[0]).toMatchObject({ key: "sig-a", member_count: 2, representative_reaction_entity_id: "rxn-1" }); });
  it("deduplicates edges and preserves merged basis plus evidence", () => { const layout = buildReactionMapFromGraphIndex({ reaction_features: [feature("rxn-a"), feature("rxn-b")], reaction_similarity_edges: [{ edge_id: "edge-1", from_reaction_entity_id: "rxn-a", to_reaction_entity_id: "rxn-b", basis: ["same_reaction_signature"], score: 0.9, warnings: ["semantic_similarity_without_computed_fingerprint"] }, { edge_id: "edge-2", from_reaction_entity_id: "rxn-b", to_reaction_entity_id: "rxn-a", basis: ["same_reaction_family"], score: 0.55, warnings: [] }] }); expect(layout.edges).toHaveLength(1); expect(layout.edges[0]).toMatchObject({ from_reaction_entity_id: "rxn-a", to_reaction_entity_id: "rxn-b", score: 0.9, confidence: "high", basis: ["same_reaction_family", "same_reaction_signature"], warnings: ["semantic_similarity_without_computed_fingerprint"] }); expect(layout.edges[0]?.evidence.map((item) => item.evidence_id)).toEqual(["edge-1", "edge-2"]); });
  it("keeps sorting and fallback layout stable", () => { const first = buildReactionMapFromGraphIndex({ reaction_features: [feature("rxn-c", { reaction_signature: "sig-c" }), feature("rxn-a", { reaction_signature: "sig-a" }), feature("rxn-b", { reaction_signature: "sig-b" })] }); const second = buildReactionMapFromGraphIndex({ reaction_features: [feature("rxn-b", { reaction_signature: "sig-b" }), feature("rxn-c", { reaction_signature: "sig-c" }), feature("rxn-a", { reaction_signature: "sig-a" })] }); expect(first.nodes).toEqual(second.nodes); expect(first.nodes.every((node) => Number.isFinite(node.x) && Number.isFinite(node.y))).toBe(true); });
  it("handles empty input and single-node input", () => { const empty = buildReactionMapFromGraphIndex({ reaction_features: [] }); const single = buildReactionMapFromGraphIndex({ reaction_features: [feature("rxn-only")] }); expect(empty.input_summary).toMatchObject({ reaction_count: 0, edge_count: 0, cluster_count: 0 }); expect(single.nodes[0]).toMatchObject({ reaction_entity_id: "rxn-only", x: 0, y: 0 }); });
  it("preserves evidence, warnings, feature refs, and worker contract data", () => { const layout = buildReactionMapFromGraphIndex({ reaction_features: [feature("rxn-a", { fingerprint_status: "external_ref_available", chemistry_feature_ref_ids: ["fp-2", "fp-1"] }), feature("rxn-b")], graph_edges: [{ edge_id: "kg-edge-1", edge_type: "supports", from_node_id: "rxn-a", to_node_id: "condition-1", document_id: "doc-1", confidence: 0.8 }], explicit_edges: [{ from_reaction_entity_id: "rxn-a", to_reaction_entity_id: "rxn-b", score: 0.7, basis: ["shared_chemistry_feature_ref"], warnings: ["external_feature_ref_no_vector_similarity"] }], warnings: ["computed_reaction_fingerprints_not_available"] }); const workerInput = toReactionMapWorkerInput(layout); expect(layout.nodes[0]).toMatchObject({ reaction_entity_id: "rxn-a", feature_refs: ["fp-1", "fp-2"], quality_tier: "external_feature_ref" }); expect(layout.nodes[0]?.evidence.map((item) => item.evidence_id)).toContain("kg-edge-1"); expect(layout.edges[0]?.warnings).toEqual(["external_feature_ref_no_vector_similarity"]); expect(layout.warnings).toEqual(["computed_reaction_fingerprints_not_available"]); expect(workerInput.edges[0]).toMatchObject({ weight: 0.7, basis: ["shared_chemistry_feature_ref"] }); });
});
