import type {
  ActivityTool,
  WorkbenchProps,
  InsightPaneProps,
} from "../../types";

export const buildInsightPaneProps = (
  activeTool: ActivityTool,
  props: WorkbenchProps,
): InsightPaneProps => ({
  activeTool,
  outline: props.output.outline,
  diagnostics: props.output.diagnostics,
  workspaceIndexViewModel: props.workspaceIndexViewModel,
  workspaceRagQueryState: props.workspaceRagQueryState,
  workspaceRagQuery: props.workspaceRagQuery,
  workspaceRagQueryOperation: props.workspaceRagQueryOperation,
  workspaceRagQueryMessage: props.workspaceRagQueryMessage,
  workspaceRagBackfillOperation: props.workspaceRagBackfillOperation,
  workspaceRagBackfillMessage: props.workspaceRagBackfillMessage,
  knowledgeMapViewModel: props.knowledgeMapViewModel,
  mode: props.mode,
  sidecarStatus: props.sidecarController.status,
  sidecarLogTail: props.sidecarController.logTail,
  sidecarOperation: props.sidecarController.operation,
  sidecarMessage: props.sidecarController.message,
  sidecarError: props.sidecarController.error,
  postgresStatus: props.postgresController.status,
  managedPostgresStatus: props.postgresController.managedStatus,
  postgresLoading: props.postgresController.loading,
  managedPostgresOperation: props.postgresController.managedOperation,
  postgresError: props.postgresController.error,
  managedPostgresError: props.postgresController.managedError,
  managedPostgresMessage: props.postgresController.managedMessage,
  postgresProfiles: props.postgresController.profiles,
  persistState: props.persistController.state,
  persistDisabledReason: props.persistController.disabledReason,
  localStoreStatus: props.localStoreController.status,
  localStoreOperation: props.localStoreController.operation,
  localSnapshotState: props.localStoreController.snapshotState,
  localSyncState: props.localStoreController.syncState,
  reactionIntelligenceJobBuild: props.reactionIntelligenceJobBuild,
  reactionIntelligenceJobState: props.reactionIntelligenceJobController.state,
  localStoreDisabledReason: props.localStoreController.disabledReason,
  localStoreSyncDisabledReason: props.localStoreController.syncDisabledReason,
  localStoreError: props.localStoreController.error,
  workspaceIngestState: props.workspaceIngestController.state,
  workspaceIngestDisabledReason: props.workspaceIngestController.disabledReason,
  workspaceSymbolIndexSummary: props.workspaceSymbolIndexController.summary,
  workspaceSymbolIndexState: props.workspaceSymbolIndexController.state,
  workspaceSymbolIndexMessage: props.workspaceSymbolIndexController.message,
  semanticPreview: props.semanticPreview,
  agentRun: props.agentRun,
  agentMessage: props.agentMessage,
  agentCurrentBeforeHash: props.agentCurrentBeforeHash,
  onStartSidecar: props.sidecarController.start,
  onStopSidecar: props.sidecarController.stop,
  onRefreshSidecar: props.sidecarController.refresh,
  onLoadSidecarLogs: props.sidecarController.loadLogs,
  onRefreshPostgres: props.postgresController.refresh,
  onInitManagedPostgres: props.postgresController.initializeManaged,
  onStartManagedPostgres: props.postgresController.startManaged,
  onStopManagedPostgres: props.postgresController.stopManaged,
  onMigrateManagedPostgres: props.postgresController.migrateManaged,
  onRefreshManagedPostgres: props.postgresController.refreshManaged,
  onPersistGraph: props.persistController.persist,
  onWorkspaceRagQueryChange: props.onWorkspaceRagQueryChange,
  onRunConnectedRagQuery: props.onRunConnectedRagQuery,
  onBackfillConnectedRagEmbeddings: props.onBackfillConnectedRagEmbeddings,
  onRefreshLocalStore: props.localStoreController.refresh,
  onSaveLocalSnapshot: props.localStoreController.saveSnapshot,
  onSyncLocalOutbox: props.localStoreController.syncPending,
  onRunReactionIntelligenceJob: props.reactionIntelligenceJobController.run,
  onRunWorkspaceIngest: props.workspaceIngestController.runIngest,
  onKnowledgeMapSourceJump: props.onKnowledgeMapSourceJump,
  onProposeQuickFix: props.onProposeQuickFix,
  onApprovePatch: props.onApprovePatch,
  onApplyPatch: props.onApplyPatch,
  onRejectPatch: props.onRejectPatch,
});
