export const MAX_DOCX_EXPORT_REQUEST_BYTES = 256 * 1024;
export const MAX_CONCURRENT_DOCX_EXPORTS = 1;
export const DOCX_EXPORT_TIMEOUT_MS = 15_000;
export const DOCX_EXPORT_BUSY_RETRY_AFTER_SECONDS = 3;
