import type { ChemdTrainingGraphIndexV1, TrainingGraphIndexEdgeV1, TrainingInferenceConfidenceV1, TrainingReactionClusterBasisV1, TrainingReactionClusterV1, TrainingReactionGraphFeatureV1, TrainingReactionSimilarityBasisV1, TrainingReactionSimilarityEdgeV1 } from "@chemd/exporter-training";

export type ReactionMapInputEdgeKind = "semantic" | "fingerprint" | "rxnfp" | "reaction_center" | "hybrid";
export type ReactionMapLayoutEngine = "deterministic_fallback" | "tmap" | "worker";
export type ReactionMapConfidence = TrainingInferenceConfidenceV1;
export type ReactionMapClusterBasis = TrainingReactionClusterBasisV1;
export type ReactionMapSimilarityBasis = TrainingReactionSimilarityBasisV1 | string;

export interface ReactionMapEvidence { evidence_id: string; source: "reaction_feature" | "reaction_cluster" | "similarity_edge" | "graph_edge" | "explicit_edge"; document_id?: string; confidence?: number | null; basis?: string[]; warnings: string[]; }
export interface ReactionMapNode { reaction_entity_id: string; document_id: string; x: number; y: number; cluster_id?: string; reaction_family?: string; procedure_signature?: string; condition_signature?: string; route_id?: string; confidence?: ReactionMapConfidence; quality_tier?: "semantic" | "external_feature_ref" | "computed"; feature_refs: string[]; warnings: string[]; evidence: ReactionMapEvidence[]; }
export interface ReactionMapEdge { edge_id: string; from_reaction_entity_id: string; to_reaction_entity_id: string; edge_kind: "similarity" | "mst"; score?: number; confidence: ReactionMapConfidence; basis: ReactionMapSimilarityBasis[]; warnings: string[]; evidence: ReactionMapEvidence[]; }
export interface ReactionMapCluster { cluster_id: string; label: string; basis: ReactionMapClusterBasis; key: string; confidence: ReactionMapConfidence; member_count: number; member_reaction_entity_ids: string[]; document_ids: string[]; representative_reaction_entity_id?: string; shared_features: string[]; warnings: string[]; training_use: { retrieval: boolean; positive_pair: boolean; eval_split_guard: boolean; requires_human_review: boolean; }; evidence: ReactionMapEvidence[]; }
export interface ReactionMapLayout { schema_version: "chemd-reaction-cluster-layout/v0.1"; layout_id: string; graph_index_id: string; source_compile_run_ids: string[]; generated_at: string; layout_engine: ReactionMapLayoutEngine; input_edge_kind: ReactionMapInputEdgeKind; input_summary: { reaction_count: number; edge_count: number; cluster_count: number; singleton_count: number; }; tmap_config: { create_mst: boolean; used_layout_from_edge_list: boolean; k?: number; kc?: number; weighted?: boolean; }; nodes: ReactionMapNode[]; edges: ReactionMapEdge[]; clusters: ReactionMapCluster[]; warnings: string[]; }
export interface ReactionMapBuildOptions { graph_index_id?: string; layout_id?: string; source_compile_run_ids?: string[]; generated_at?: string; input_edge_kind?: ReactionMapInputEdgeKind; }
export interface ReactionMapExplicitEdgeInput { edge_id?: string; from_reaction_entity_id: string; to_reaction_entity_id: string; score?: number; basis: ReactionMapSimilarityBasis[]; warnings?: string[]; evidence?: ReactionMapEvidence[]; }
export interface ReactionMapExplicitInput { graph_index_id?: string; source_compile_run_ids?: string[]; reaction_features: TrainingReactionGraphFeatureV1[]; reaction_clusters?: TrainingReactionClusterV1[]; reaction_similarity_edges?: TrainingReactionSimilarityEdgeV1[]; explicit_edges?: ReactionMapExplicitEdgeInput[]; graph_edges?: TrainingGraphIndexEdgeV1[]; warnings?: string[]; }
export type ReactionMapBuildInput = ChemdTrainingGraphIndexV1 | ReactionMapExplicitInput;
export interface ReactionMapWorkerLayoutInput { layout_id: string; input_edge_kind: ReactionMapInputEdgeKind; reactions: string[]; edges: Array<{ from_reaction_entity_id: string; to_reaction_entity_id: string; weight: number; basis: ReactionMapSimilarityBasis[]; }>; feature_refs: Array<{ reaction_entity_id: string; feature_ref_ids: string[]; }>; }
export interface ReactionMapWorkerLayoutOutput { layout_engine: "tmap" | "worker"; layout_engine_version?: string; positions: Array<{ reaction_entity_id: string; x: number; y: number; }>; mst_edges?: Array<{ from_reaction_entity_id: string; to_reaction_entity_id: string; weight?: number; }>; warnings: string[]; }
export interface ReactionMapLayoutWorkerAdapter { layout(input: ReactionMapWorkerLayoutInput): Promise<ReactionMapWorkerLayoutOutput>; }

const uniqueStrings = (values: readonly string[]): string[] => Array.from(new Set(values.filter(Boolean))).sort();
const compareStrings = (left: string, right: string): number => left.localeCompare(right, "en");
const createStableHash = (value: string): string => { let hash = 2166136261; for (let i = 0; i < value.length; i += 1) { hash ^= value.charCodeAt(i); hash = Math.imul(hash, 16777619); } return (hash >>> 0).toString(16).padStart(8, "0"); };
const confidenceFromScore = (score: number | undefined): ReactionMapConfidence => score === undefined ? "low" : score >= 0.85 ? "high" : score >= 0.65 ? "medium" : "low";
const clusterRank = (basis: ReactionMapClusterBasis): number => ({ reaction_signature: 1, chemistry_feature_ref: 2, family_procedure: 3, procedure_signature: 4, condition_signature: 5, reaction_family: 6, route: 7, campaign_trajectory: 8 })[basis] ?? 99;
const confidenceForBasis = (basis: ReactionMapClusterBasis): ReactionMapConfidence => basis === "reaction_signature" || basis === "chemistry_feature_ref" ? "high" : basis === "family_procedure" || basis === "campaign_trajectory" || basis === "route" ? "medium" : "low";
const warningsForBasis = (basis: ReactionMapClusterBasis): string[] => basis === "chemistry_feature_ref" ? ["external_feature_ref_no_vector_similarity"] : basis === "reaction_family" ? ["family_only_cluster_review_required"] : ["semantic_cluster_no_computed_chemical_fingerprint"];
const featureEvidence = (feature: TrainingReactionGraphFeatureV1): ReactionMapEvidence => ({ evidence_id: `reaction-feature::${feature.reaction_entity_id}`, source: "reaction_feature", document_id: feature.document_id, warnings: feature.fingerprint_status === "not_available" ? ["computed_reaction_fingerprint_not_available"] : [] });
const compareClusters = (left: ReactionMapCluster, right: ReactionMapCluster): number => clusterRank(left.basis) - clusterRank(right.basis) || compareStrings(left.key, right.key) || compareStrings(left.cluster_id, right.cluster_id);
const trainingUse = (confidence: ReactionMapConfidence, warnings: readonly string[], memberCount: number): ReactionMapCluster["training_use"] => ({ retrieval: memberCount > 0, positive_pair: confidence === "high" && memberCount > 1 && warnings.length === 0, eval_split_guard: memberCount > 1, requires_human_review: confidence === "low" || warnings.length > 0 });

const buildDerivedClusters = (features: readonly TrainingReactionGraphFeatureV1[]): ReactionMapCluster[] => {
  const groups = new Map<string, TrainingReactionGraphFeatureV1[]>();
  features.forEach((feature) => feature.cluster_keys.forEach((item) => { const key = `${item.basis}\u0000${item.key}`; groups.set(key, [...(groups.get(key) ?? []), feature]); }));
  return Array.from(groups.entries()).map(([compoundKey, members]) => {
    const [basis, key] = compoundKey.split("\u0000") as [ReactionMapClusterBasis, string];
    const memberIds = uniqueStrings(members.map((member) => member.reaction_entity_id));
    const confidence = confidenceForBasis(basis);
    const warnings = warningsForBasis(basis);
    return { cluster_id: `reaction-cluster::${basis}::${createStableHash(key)}`, label: `${basis}: ${key}`, basis, key, confidence, member_count: memberIds.length, member_reaction_entity_ids: memberIds, document_ids: uniqueStrings(members.map((member) => member.document_id)), representative_reaction_entity_id: memberIds[0], shared_features: [key], warnings, training_use: trainingUse(confidence, warnings, memberIds.length), evidence: members.map(featureEvidence) };
  }).sort(compareClusters);
};

const mergeProvidedClusters = (derived: readonly ReactionMapCluster[], provided: readonly TrainingReactionClusterV1[]): ReactionMapCluster[] => {
  const byId = new Map(derived.map((cluster) => [cluster.cluster_id, cluster]));
  provided.forEach((cluster) => { const memberIds = uniqueStrings(cluster.member_reaction_entity_ids); const warnings = uniqueStrings(cluster.warnings); byId.set(cluster.cluster_id, { cluster_id: cluster.cluster_id, label: `${cluster.basis}: ${cluster.key}`, basis: cluster.basis, key: cluster.key, confidence: cluster.confidence, member_count: memberIds.length, member_reaction_entity_ids: memberIds, document_ids: uniqueStrings(cluster.document_ids), representative_reaction_entity_id: memberIds[0], shared_features: uniqueStrings(cluster.shared_features), warnings, training_use: trainingUse(cluster.confidence, warnings, memberIds.length), evidence: [{ evidence_id: cluster.cluster_id, source: "reaction_cluster", basis: [cluster.basis], warnings }] }); });
  return [...byId.values()].sort(compareClusters);
};

const graphEvidence = (graphEdges: readonly TrainingGraphIndexEdgeV1[], reactionId: string): ReactionMapEvidence[] => graphEdges.filter((edge) => edge.from_node_id === reactionId || edge.to_node_id === reactionId).map((edge) => ({ evidence_id: edge.edge_id, source: "graph_edge", document_id: edge.document_id, confidence: edge.confidence, warnings: [] }));
const buildNodes = (features: readonly TrainingReactionGraphFeatureV1[], clusters: readonly ReactionMapCluster[], graphEdges: readonly TrainingGraphIndexEdgeV1[]): ReactionMapNode[] => features.map((feature) => { const cluster = clusters.filter((item) => item.member_reaction_entity_ids.includes(feature.reaction_entity_id)).sort(compareClusters)[0]; const qualityTier: ReactionMapNode["quality_tier"] = feature.fingerprint_status === "external_ref_available" ? "external_feature_ref" : "semantic"; return { reaction_entity_id: feature.reaction_entity_id, document_id: feature.document_id, x: 0, y: 0, cluster_id: cluster?.cluster_id, reaction_family: feature.reaction_family, procedure_signature: feature.procedure_signature, condition_signature: feature.condition_signature, route_id: feature.route_id, confidence: cluster?.confidence, quality_tier: qualityTier, feature_refs: uniqueStrings(feature.chemistry_feature_ref_ids), warnings: feature.fingerprint_status === "not_available" ? ["computed_reaction_fingerprint_not_available"] : [], evidence: [featureEvidence(feature), ...graphEvidence(graphEdges, feature.reaction_entity_id)] }; }).sort((left, right) => compareStrings(left.reaction_entity_id, right.reaction_entity_id));
const normalizedSimilarity = (edge: TrainingReactionSimilarityEdgeV1): ReactionMapExplicitEdgeInput => ({ edge_id: edge.edge_id, from_reaction_entity_id: edge.from_reaction_entity_id, to_reaction_entity_id: edge.to_reaction_entity_id, score: edge.score, basis: edge.basis, warnings: edge.warnings, evidence: [{ evidence_id: edge.edge_id, source: "similarity_edge", basis: edge.basis, warnings: edge.warnings }] });

const buildEdges = (similarityEdges: readonly TrainingReactionSimilarityEdgeV1[], explicitEdges: readonly ReactionMapExplicitEdgeInput[]): ReactionMapEdge[] => {
  const merged = new Map<string, ReactionMapEdge>();
  [...similarityEdges.map(normalizedSimilarity), ...explicitEdges].forEach((edge) => { if (edge.from_reaction_entity_id === edge.to_reaction_entity_id) return; const pair = [edge.from_reaction_entity_id, edge.to_reaction_entity_id].sort(compareStrings); const key = `${pair[0]}::${pair[1]}`; const existing = merged.get(key); const basis = uniqueStrings([...(existing?.basis ?? []), ...edge.basis]); const warnings = uniqueStrings([...(existing?.warnings ?? []), ...(edge.warnings ?? [])]); const score = Math.max(existing?.score ?? 0, edge.score ?? 0); merged.set(key, { edge_id: `reaction-map-edge::${createStableHash(`${key}::${basis.join("|")}`)}`, from_reaction_entity_id: pair[0] ?? "", to_reaction_entity_id: pair[1] ?? "", edge_kind: "similarity", score, confidence: confidenceFromScore(score), basis, warnings, evidence: [...(existing?.evidence ?? []), ...(edge.evidence ?? [])] }); });
  return [...merged.values()].sort((left, right) => compareStrings(left.edge_id, right.edge_id));
};

const applyFallbackLayout = (nodes: readonly ReactionMapNode[]): ReactionMapNode[] => { if (nodes.length < 2) return nodes.map((node) => ({ ...node, x: 0, y: 0 })); const radius = Math.max(64, nodes.length * 24); return nodes.map((node, index) => { const angle = (Math.PI * 2 * index) / nodes.length; return { ...node, x: Number((Math.cos(angle) * radius).toFixed(6)), y: Number((Math.sin(angle) * radius).toFixed(6)) }; }); };
const isGraphIndexInput = (input: ReactionMapBuildInput): input is ChemdTrainingGraphIndexV1 => "schema_version" in input && input.schema_version === "chemd-training-graph-index/v0.1";
const normalizeInput = (input: ReactionMapBuildInput, options: ReactionMapBuildOptions): ReactionMapExplicitInput => isGraphIndexInput(input) ? { graph_index_id: options.graph_index_id, source_compile_run_ids: options.source_compile_run_ids ?? input.index_scope.document_ids, reaction_features: input.reaction_features, reaction_clusters: input.reaction_clusters, reaction_similarity_edges: input.reaction_similarity_edges, graph_edges: input.edges, warnings: input.warnings } : input;

export const buildReactionMapFromGraphIndex = (input: ReactionMapBuildInput, options: ReactionMapBuildOptions = {}): ReactionMapLayout => {
  const normalized = normalizeInput(input, options);
  const graphIndexId = options.graph_index_id ?? normalized.graph_index_id ?? "graph-index::explicit";
  const clusters = mergeProvidedClusters(buildDerivedClusters(normalized.reaction_features), normalized.reaction_clusters ?? []);
  const nodes = applyFallbackLayout(buildNodes(normalized.reaction_features, clusters, normalized.graph_edges ?? []));
  const edges = buildEdges(normalized.reaction_similarity_edges ?? [], normalized.explicit_edges ?? []);
  return { schema_version: "chemd-reaction-cluster-layout/v0.1", layout_id: options.layout_id ?? `reaction-layout::${createStableHash(graphIndexId)}`, graph_index_id: graphIndexId, source_compile_run_ids: options.source_compile_run_ids ?? normalized.source_compile_run_ids ?? [], generated_at: options.generated_at ?? "1970-01-01T00:00:00.000Z", layout_engine: "deterministic_fallback", input_edge_kind: options.input_edge_kind ?? "semantic", input_summary: { reaction_count: nodes.length, edge_count: edges.length, cluster_count: clusters.length, singleton_count: clusters.filter((cluster) => cluster.member_count === 1).length }, tmap_config: { create_mst: false, used_layout_from_edge_list: false, weighted: true }, nodes, edges, clusters, warnings: uniqueStrings(normalized.warnings ?? []) };
};

export const toReactionMapWorkerInput = (layout: ReactionMapLayout): ReactionMapWorkerLayoutInput => ({ layout_id: layout.layout_id, input_edge_kind: layout.input_edge_kind, reactions: layout.nodes.map((node) => node.reaction_entity_id).sort(compareStrings), edges: layout.edges.map((edge) => ({ from_reaction_entity_id: edge.from_reaction_entity_id, to_reaction_entity_id: edge.to_reaction_entity_id, weight: edge.score ?? 0, basis: edge.basis })), feature_refs: layout.nodes.map((node) => ({ reaction_entity_id: node.reaction_entity_id, feature_ref_ids: node.feature_refs })) });
